/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the OrderCancelledCallbackResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCancelledCallbackResp{}

// OrderCancelledCallbackResp struct for OrderCancelledCallbackResp
type OrderCancelledCallbackResp struct {
	// The time this callback was sent in ISO8601 format
	Timestamp time.Time `json:"timestamp"`
	// The ID of the order
	OrderId string `json:"orderId"`
	CancellationFee *Price1 `json:"cancellationFee,omitempty"`
}

// NewOrderCancelledCallbackResp instantiates a new OrderCancelledCallbackResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCancelledCallbackResp(timestamp time.Time, orderId string) *OrderCancelledCallbackResp {
	this := OrderCancelledCallbackResp{}
	this.Timestamp = timestamp
	this.OrderId = orderId
	return &this
}

// NewOrderCancelledCallbackRespWithDefaults instantiates a new OrderCancelledCallbackResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCancelledCallbackRespWithDefaults() *OrderCancelledCallbackResp {
	this := OrderCancelledCallbackResp{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *OrderCancelledCallbackResp) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *OrderCancelledCallbackResp) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *OrderCancelledCallbackResp) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetOrderId returns the OrderId field value
func (o *OrderCancelledCallbackResp) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *OrderCancelledCallbackResp) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *OrderCancelledCallbackResp) SetOrderId(v string) {
	o.OrderId = v
}

// GetCancellationFee returns the CancellationFee field value if set, zero value otherwise.
func (o *OrderCancelledCallbackResp) GetCancellationFee() Price1 {
	if o == nil || IsNil(o.CancellationFee) {
		var ret Price1
		return ret
	}
	return *o.CancellationFee
}

// GetCancellationFeeOk returns a tuple with the CancellationFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCancelledCallbackResp) GetCancellationFeeOk() (*Price1, bool) {
	if o == nil || IsNil(o.CancellationFee) {
		return nil, false
	}
	return o.CancellationFee, true
}

// HasCancellationFee returns a boolean if a field has been set.
func (o *OrderCancelledCallbackResp) HasCancellationFee() bool {
	if o != nil && !IsNil(o.CancellationFee) {
		return true
	}

	return false
}

// SetCancellationFee gets a reference to the given Price1 and assigns it to the CancellationFee field.
func (o *OrderCancelledCallbackResp) SetCancellationFee(v Price1) {
	o.CancellationFee = &v
}

func (o OrderCancelledCallbackResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCancelledCallbackResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["orderId"] = o.OrderId
	if !IsNil(o.CancellationFee) {
		toSerialize["cancellationFee"] = o.CancellationFee
	}
	return toSerialize, nil
}

type NullableOrderCancelledCallbackResp struct {
	value *OrderCancelledCallbackResp
	isSet bool
}

func (v NullableOrderCancelledCallbackResp) Get() *OrderCancelledCallbackResp {
	return v.value
}

func (v *NullableOrderCancelledCallbackResp) Set(val *OrderCancelledCallbackResp) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCancelledCallbackResp) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCancelledCallbackResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCancelledCallbackResp(val *OrderCancelledCallbackResp) *NullableOrderCancelledCallbackResp {
	return &NullableOrderCancelledCallbackResp{value: val, isSet: true}
}

func (v NullableOrderCancelledCallbackResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCancelledCallbackResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


