/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the OrderOrderIdDelete402Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderOrderIdDelete402Response{}

// OrderOrderIdDelete402Response struct for OrderOrderIdDelete402Response
type OrderOrderIdDelete402Response struct {
	Payment *Price `json:"payment,omitempty"`
	// A token that should be returned in order to confirm the cancellation. To confirm the cancellation, pass this in an X-EVERMILE-TOKEN header.
	Token *string `json:"token,omitempty"`
}

// NewOrderOrderIdDelete402Response instantiates a new OrderOrderIdDelete402Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderOrderIdDelete402Response() *OrderOrderIdDelete402Response {
	this := OrderOrderIdDelete402Response{}
	return &this
}

// NewOrderOrderIdDelete402ResponseWithDefaults instantiates a new OrderOrderIdDelete402Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderOrderIdDelete402ResponseWithDefaults() *OrderOrderIdDelete402Response {
	this := OrderOrderIdDelete402Response{}
	return &this
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *OrderOrderIdDelete402Response) GetPayment() Price {
	if o == nil || IsNil(o.Payment) {
		var ret Price
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderIdDelete402Response) GetPaymentOk() (*Price, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *OrderOrderIdDelete402Response) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given Price and assigns it to the Payment field.
func (o *OrderOrderIdDelete402Response) SetPayment(v Price) {
	o.Payment = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *OrderOrderIdDelete402Response) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderIdDelete402Response) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *OrderOrderIdDelete402Response) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *OrderOrderIdDelete402Response) SetToken(v string) {
	o.Token = &v
}

func (o OrderOrderIdDelete402Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderOrderIdDelete402Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableOrderOrderIdDelete402Response struct {
	value *OrderOrderIdDelete402Response
	isSet bool
}

func (v NullableOrderOrderIdDelete402Response) Get() *OrderOrderIdDelete402Response {
	return v.value
}

func (v *NullableOrderOrderIdDelete402Response) Set(val *OrderOrderIdDelete402Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderOrderIdDelete402Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderOrderIdDelete402Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderOrderIdDelete402Response(val *OrderOrderIdDelete402Response) *NullableOrderOrderIdDelete402Response {
	return &NullableOrderOrderIdDelete402Response{value: val, isSet: true}
}

func (v NullableOrderOrderIdDelete402Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderOrderIdDelete402Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


