/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the OrderCreatedCallbackResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreatedCallbackResp{}

// OrderCreatedCallbackResp struct for OrderCreatedCallbackResp
type OrderCreatedCallbackResp struct {
	// The time this callback was sent in ISO8601 format
	Timestamp time.Time `json:"timestamp"`
	Order OrderDetails1 `json:"order"`
}

// NewOrderCreatedCallbackResp instantiates a new OrderCreatedCallbackResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreatedCallbackResp(timestamp time.Time, order OrderDetails1) *OrderCreatedCallbackResp {
	this := OrderCreatedCallbackResp{}
	this.Timestamp = timestamp
	this.Order = order
	return &this
}

// NewOrderCreatedCallbackRespWithDefaults instantiates a new OrderCreatedCallbackResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreatedCallbackRespWithDefaults() *OrderCreatedCallbackResp {
	this := OrderCreatedCallbackResp{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *OrderCreatedCallbackResp) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *OrderCreatedCallbackResp) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *OrderCreatedCallbackResp) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetOrder returns the Order field value
func (o *OrderCreatedCallbackResp) GetOrder() OrderDetails1 {
	if o == nil {
		var ret OrderDetails1
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *OrderCreatedCallbackResp) GetOrderOk() (*OrderDetails1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *OrderCreatedCallbackResp) SetOrder(v OrderDetails1) {
	o.Order = v
}

func (o OrderCreatedCallbackResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreatedCallbackResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

type NullableOrderCreatedCallbackResp struct {
	value *OrderCreatedCallbackResp
	isSet bool
}

func (v NullableOrderCreatedCallbackResp) Get() *OrderCreatedCallbackResp {
	return v.value
}

func (v *NullableOrderCreatedCallbackResp) Set(val *OrderCreatedCallbackResp) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreatedCallbackResp) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreatedCallbackResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreatedCallbackResp(val *OrderCreatedCallbackResp) *NullableOrderCreatedCallbackResp {
	return &NullableOrderCreatedCallbackResp{value: val, isSet: true}
}

func (v NullableOrderCreatedCallbackResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreatedCallbackResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


