/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the OrderCollectedCallbackResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCollectedCallbackResp{}

// OrderCollectedCallbackResp struct for OrderCollectedCallbackResp
type OrderCollectedCallbackResp struct {
	// The time this callback was sent in ISO8601 format
	Timestamp time.Time `json:"timestamp"`
	// The ID of the order
	OrderId string `json:"orderId"`
}

// NewOrderCollectedCallbackResp instantiates a new OrderCollectedCallbackResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCollectedCallbackResp(timestamp time.Time, orderId string) *OrderCollectedCallbackResp {
	this := OrderCollectedCallbackResp{}
	this.Timestamp = timestamp
	this.OrderId = orderId
	return &this
}

// NewOrderCollectedCallbackRespWithDefaults instantiates a new OrderCollectedCallbackResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCollectedCallbackRespWithDefaults() *OrderCollectedCallbackResp {
	this := OrderCollectedCallbackResp{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *OrderCollectedCallbackResp) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *OrderCollectedCallbackResp) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *OrderCollectedCallbackResp) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetOrderId returns the OrderId field value
func (o *OrderCollectedCallbackResp) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *OrderCollectedCallbackResp) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *OrderCollectedCallbackResp) SetOrderId(v string) {
	o.OrderId = v
}

func (o OrderCollectedCallbackResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCollectedCallbackResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["orderId"] = o.OrderId
	return toSerialize, nil
}

type NullableOrderCollectedCallbackResp struct {
	value *OrderCollectedCallbackResp
	isSet bool
}

func (v NullableOrderCollectedCallbackResp) Get() *OrderCollectedCallbackResp {
	return v.value
}

func (v *NullableOrderCollectedCallbackResp) Set(val *OrderCollectedCallbackResp) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCollectedCallbackResp) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCollectedCallbackResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCollectedCallbackResp(val *OrderCollectedCallbackResp) *NullableOrderCollectedCallbackResp {
	return &NullableOrderCollectedCallbackResp{value: val, isSet: true}
}

func (v NullableOrderCollectedCallbackResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCollectedCallbackResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


