/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the InvalidAddressBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidAddressBody{}

// InvalidAddressBody struct for InvalidAddressBody
type InvalidAddressBody struct {
	// The error message
	Message *string `json:"message,omitempty"`
	Input AddressComponents `json:"input"`
}

// NewInvalidAddressBody instantiates a new InvalidAddressBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidAddressBody(input AddressComponents) *InvalidAddressBody {
	this := InvalidAddressBody{}
	this.Input = input
	return &this
}

// NewInvalidAddressBodyWithDefaults instantiates a new InvalidAddressBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidAddressBodyWithDefaults() *InvalidAddressBody {
	this := InvalidAddressBody{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InvalidAddressBody) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvalidAddressBody) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InvalidAddressBody) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InvalidAddressBody) SetMessage(v string) {
	o.Message = &v
}

// GetInput returns the Input field value
func (o *InvalidAddressBody) GetInput() AddressComponents {
	if o == nil {
		var ret AddressComponents
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *InvalidAddressBody) GetInputOk() (*AddressComponents, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *InvalidAddressBody) SetInput(v AddressComponents) {
	o.Input = v
}

func (o InvalidAddressBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidAddressBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	toSerialize["input"] = o.Input
	return toSerialize, nil
}

type NullableInvalidAddressBody struct {
	value *InvalidAddressBody
	isSet bool
}

func (v NullableInvalidAddressBody) Get() *InvalidAddressBody {
	return v.value
}

func (v *NullableInvalidAddressBody) Set(val *InvalidAddressBody) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidAddressBody) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidAddressBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidAddressBody(val *InvalidAddressBody) *NullableInvalidAddressBody {
	return &NullableInvalidAddressBody{value: val, isSet: true}
}

func (v NullableInvalidAddressBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidAddressBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


