/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the DeliverySlot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliverySlot{}

// DeliverySlot A slot of time
type DeliverySlot struct {
	// The start time in ISO8601 format
	Start time.Time `json:"start"`
	// The end time in ISO8601 format
	End time.Time `json:"end"`
}

// NewDeliverySlot instantiates a new DeliverySlot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliverySlot(start time.Time, end time.Time) *DeliverySlot {
	this := DeliverySlot{}
	this.Start = start
	this.End = end
	return &this
}

// NewDeliverySlotWithDefaults instantiates a new DeliverySlot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliverySlotWithDefaults() *DeliverySlot {
	this := DeliverySlot{}
	return &this
}

// GetStart returns the Start field value
func (o *DeliverySlot) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *DeliverySlot) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *DeliverySlot) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *DeliverySlot) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *DeliverySlot) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *DeliverySlot) SetEnd(v time.Time) {
	o.End = v
}

func (o DeliverySlot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliverySlot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

type NullableDeliverySlot struct {
	value *DeliverySlot
	isSet bool
}

func (v NullableDeliverySlot) Get() *DeliverySlot {
	return v.value
}

func (v *NullableDeliverySlot) Set(val *DeliverySlot) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliverySlot) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliverySlot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliverySlot(val *DeliverySlot) *NullableDeliverySlot {
	return &NullableDeliverySlot{value: val, isSet: true}
}

func (v NullableDeliverySlot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliverySlot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


