/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the OptionalTimeWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OptionalTimeWindow{}

// OptionalTimeWindow A slot of time
type OptionalTimeWindow struct {
	// The start time in ISO8601 format
	Start *time.Time `json:"start,omitempty"`
	// The end time in ISO8601 format
	End *time.Time `json:"end,omitempty"`
}

// NewOptionalTimeWindow instantiates a new OptionalTimeWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionalTimeWindow() *OptionalTimeWindow {
	this := OptionalTimeWindow{}
	return &this
}

// NewOptionalTimeWindowWithDefaults instantiates a new OptionalTimeWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionalTimeWindowWithDefaults() *OptionalTimeWindow {
	this := OptionalTimeWindow{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *OptionalTimeWindow) GetStart() time.Time {
	if o == nil || IsNil(o.Start) {
		var ret time.Time
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionalTimeWindow) GetStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *OptionalTimeWindow) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given time.Time and assigns it to the Start field.
func (o *OptionalTimeWindow) SetStart(v time.Time) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *OptionalTimeWindow) GetEnd() time.Time {
	if o == nil || IsNil(o.End) {
		var ret time.Time
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionalTimeWindow) GetEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *OptionalTimeWindow) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given time.Time and assigns it to the End field.
func (o *OptionalTimeWindow) SetEnd(v time.Time) {
	o.End = &v
}

func (o OptionalTimeWindow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OptionalTimeWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	return toSerialize, nil
}

type NullableOptionalTimeWindow struct {
	value *OptionalTimeWindow
	isSet bool
}

func (v NullableOptionalTimeWindow) Get() *OptionalTimeWindow {
	return v.value
}

func (v *NullableOptionalTimeWindow) Set(val *OptionalTimeWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionalTimeWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionalTimeWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionalTimeWindow(val *OptionalTimeWindow) *NullableOptionalTimeWindow {
	return &NullableOptionalTimeWindow{value: val, isSet: true}
}

func (v NullableOptionalTimeWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionalTimeWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


