/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the OrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderRequest{}

// OrderRequest Parameters for an order request
type OrderRequest struct {
	// The proposal ID to create order from
	ProposalId string `json:"proposalId"`
	// An external order ID to attach to this order
	ExternalOrderId *string `json:"externalOrderId,omitempty"`
	PickupContactDetails *ContactDetails `json:"pickupContactDetails,omitempty"`
	// The id of an existing sender location with the sender contact details
	PickupLocationId *string `json:"pickupLocationId,omitempty"`
	DropoffContactDetails ContactDetails `json:"dropoffContactDetails"`
	// Whether to use available credits to pay for order
	UseCredits bool `json:"useCredits"`
	// Proof of delivery requirements for a parcel, Optional. Will override any POD passed in on the quote
	ProofOfDeliveryRequirement []ProofOfDeliveryRequirement `json:"proofOfDeliveryRequirement,omitempty"`
}

// NewOrderRequest instantiates a new OrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderRequest(proposalId string, dropoffContactDetails ContactDetails, useCredits bool) *OrderRequest {
	this := OrderRequest{}
	this.ProposalId = proposalId
	var externalOrderId string = ""
	this.ExternalOrderId = &externalOrderId
	this.DropoffContactDetails = dropoffContactDetails
	this.UseCredits = useCredits
	return &this
}

// NewOrderRequestWithDefaults instantiates a new OrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderRequestWithDefaults() *OrderRequest {
	this := OrderRequest{}
	var externalOrderId string = ""
	this.ExternalOrderId = &externalOrderId
	var useCredits bool = false
	this.UseCredits = useCredits
	return &this
}

// GetProposalId returns the ProposalId field value
func (o *OrderRequest) GetProposalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProposalId
}

// GetProposalIdOk returns a tuple with the ProposalId field value
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetProposalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProposalId, true
}

// SetProposalId sets field value
func (o *OrderRequest) SetProposalId(v string) {
	o.ProposalId = v
}

// GetExternalOrderId returns the ExternalOrderId field value if set, zero value otherwise.
func (o *OrderRequest) GetExternalOrderId() string {
	if o == nil || IsNil(o.ExternalOrderId) {
		var ret string
		return ret
	}
	return *o.ExternalOrderId
}

// GetExternalOrderIdOk returns a tuple with the ExternalOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetExternalOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalOrderId) {
		return nil, false
	}
	return o.ExternalOrderId, true
}

// HasExternalOrderId returns a boolean if a field has been set.
func (o *OrderRequest) HasExternalOrderId() bool {
	if o != nil && !IsNil(o.ExternalOrderId) {
		return true
	}

	return false
}

// SetExternalOrderId gets a reference to the given string and assigns it to the ExternalOrderId field.
func (o *OrderRequest) SetExternalOrderId(v string) {
	o.ExternalOrderId = &v
}

// GetPickupContactDetails returns the PickupContactDetails field value if set, zero value otherwise.
func (o *OrderRequest) GetPickupContactDetails() ContactDetails {
	if o == nil || IsNil(o.PickupContactDetails) {
		var ret ContactDetails
		return ret
	}
	return *o.PickupContactDetails
}

// GetPickupContactDetailsOk returns a tuple with the PickupContactDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetPickupContactDetailsOk() (*ContactDetails, bool) {
	if o == nil || IsNil(o.PickupContactDetails) {
		return nil, false
	}
	return o.PickupContactDetails, true
}

// HasPickupContactDetails returns a boolean if a field has been set.
func (o *OrderRequest) HasPickupContactDetails() bool {
	if o != nil && !IsNil(o.PickupContactDetails) {
		return true
	}

	return false
}

// SetPickupContactDetails gets a reference to the given ContactDetails and assigns it to the PickupContactDetails field.
func (o *OrderRequest) SetPickupContactDetails(v ContactDetails) {
	o.PickupContactDetails = &v
}

// GetPickupLocationId returns the PickupLocationId field value if set, zero value otherwise.
func (o *OrderRequest) GetPickupLocationId() string {
	if o == nil || IsNil(o.PickupLocationId) {
		var ret string
		return ret
	}
	return *o.PickupLocationId
}

// GetPickupLocationIdOk returns a tuple with the PickupLocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetPickupLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.PickupLocationId) {
		return nil, false
	}
	return o.PickupLocationId, true
}

// HasPickupLocationId returns a boolean if a field has been set.
func (o *OrderRequest) HasPickupLocationId() bool {
	if o != nil && !IsNil(o.PickupLocationId) {
		return true
	}

	return false
}

// SetPickupLocationId gets a reference to the given string and assigns it to the PickupLocationId field.
func (o *OrderRequest) SetPickupLocationId(v string) {
	o.PickupLocationId = &v
}

// GetDropoffContactDetails returns the DropoffContactDetails field value
func (o *OrderRequest) GetDropoffContactDetails() ContactDetails {
	if o == nil {
		var ret ContactDetails
		return ret
	}

	return o.DropoffContactDetails
}

// GetDropoffContactDetailsOk returns a tuple with the DropoffContactDetails field value
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetDropoffContactDetailsOk() (*ContactDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DropoffContactDetails, true
}

// SetDropoffContactDetails sets field value
func (o *OrderRequest) SetDropoffContactDetails(v ContactDetails) {
	o.DropoffContactDetails = v
}

// GetUseCredits returns the UseCredits field value
func (o *OrderRequest) GetUseCredits() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseCredits
}

// GetUseCreditsOk returns a tuple with the UseCredits field value
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetUseCreditsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UseCredits, true
}

// SetUseCredits sets field value
func (o *OrderRequest) SetUseCredits(v bool) {
	o.UseCredits = v
}

// GetProofOfDeliveryRequirement returns the ProofOfDeliveryRequirement field value if set, zero value otherwise.
func (o *OrderRequest) GetProofOfDeliveryRequirement() []ProofOfDeliveryRequirement {
	if o == nil || IsNil(o.ProofOfDeliveryRequirement) {
		var ret []ProofOfDeliveryRequirement
		return ret
	}
	return o.ProofOfDeliveryRequirement
}

// GetProofOfDeliveryRequirementOk returns a tuple with the ProofOfDeliveryRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderRequest) GetProofOfDeliveryRequirementOk() ([]ProofOfDeliveryRequirement, bool) {
	if o == nil || IsNil(o.ProofOfDeliveryRequirement) {
		return nil, false
	}
	return o.ProofOfDeliveryRequirement, true
}

// HasProofOfDeliveryRequirement returns a boolean if a field has been set.
func (o *OrderRequest) HasProofOfDeliveryRequirement() bool {
	if o != nil && !IsNil(o.ProofOfDeliveryRequirement) {
		return true
	}

	return false
}

// SetProofOfDeliveryRequirement gets a reference to the given []ProofOfDeliveryRequirement and assigns it to the ProofOfDeliveryRequirement field.
func (o *OrderRequest) SetProofOfDeliveryRequirement(v []ProofOfDeliveryRequirement) {
	o.ProofOfDeliveryRequirement = v
}

func (o OrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proposalId"] = o.ProposalId
	if !IsNil(o.ExternalOrderId) {
		toSerialize["externalOrderId"] = o.ExternalOrderId
	}
	if !IsNil(o.PickupContactDetails) {
		toSerialize["pickupContactDetails"] = o.PickupContactDetails
	}
	if !IsNil(o.PickupLocationId) {
		toSerialize["pickupLocationId"] = o.PickupLocationId
	}
	toSerialize["dropoffContactDetails"] = o.DropoffContactDetails
	toSerialize["useCredits"] = o.UseCredits
	if !IsNil(o.ProofOfDeliveryRequirement) {
		toSerialize["proofOfDeliveryRequirement"] = o.ProofOfDeliveryRequirement
	}
	return toSerialize, nil
}

type NullableOrderRequest struct {
	value *OrderRequest
	isSet bool
}

func (v NullableOrderRequest) Get() *OrderRequest {
	return v.value
}

func (v *NullableOrderRequest) Set(val *OrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderRequest(val *OrderRequest) *NullableOrderRequest {
	return &NullableOrderRequest{value: val, isSet: true}
}

func (v NullableOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


