/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the LocationResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationResp{}

// LocationResp struct for LocationResp
type LocationResp struct {
	// The new delivery location ID
	Id string `json:"id"`
}

// NewLocationResp instantiates a new LocationResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationResp(id string) *LocationResp {
	this := LocationResp{}
	this.Id = id
	return &this
}

// NewLocationRespWithDefaults instantiates a new LocationResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationRespWithDefaults() *LocationResp {
	this := LocationResp{}
	return &this
}

// GetId returns the Id field value
func (o *LocationResp) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LocationResp) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LocationResp) SetId(v string) {
	o.Id = v
}

func (o LocationResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableLocationResp struct {
	value *LocationResp
	isSet bool
}

func (v NullableLocationResp) Get() *LocationResp {
	return v.value
}

func (v *NullableLocationResp) Set(val *LocationResp) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationResp) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationResp(val *LocationResp) *NullableLocationResp {
	return &NullableLocationResp{value: val, isSet: true}
}

func (v NullableLocationResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


