/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the WebhookPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPostResponse{}

// WebhookPostResponse The response from a webhook creation request
type WebhookPostResponse struct {
	Webhook Webhook `json:"webhook"`
	// The public key from a keypair used to validate the HMAC signature for a call from this webhook.
	Secret string `json:"secret"`
}

// NewWebhookPostResponse instantiates a new WebhookPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPostResponse(webhook Webhook, secret string) *WebhookPostResponse {
	this := WebhookPostResponse{}
	this.Webhook = webhook
	this.Secret = secret
	return &this
}

// NewWebhookPostResponseWithDefaults instantiates a new WebhookPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPostResponseWithDefaults() *WebhookPostResponse {
	this := WebhookPostResponse{}
	return &this
}

// GetWebhook returns the Webhook field value
func (o *WebhookPostResponse) GetWebhook() Webhook {
	if o == nil {
		var ret Webhook
		return ret
	}

	return o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value
// and a boolean to check if the value has been set.
func (o *WebhookPostResponse) GetWebhookOk() (*Webhook, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Webhook, true
}

// SetWebhook sets field value
func (o *WebhookPostResponse) SetWebhook(v Webhook) {
	o.Webhook = v
}

// GetSecret returns the Secret field value
func (o *WebhookPostResponse) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *WebhookPostResponse) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *WebhookPostResponse) SetSecret(v string) {
	o.Secret = v
}

func (o WebhookPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhook"] = o.Webhook
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

type NullableWebhookPostResponse struct {
	value *WebhookPostResponse
	isSet bool
}

func (v NullableWebhookPostResponse) Get() *WebhookPostResponse {
	return v.value
}

func (v *NullableWebhookPostResponse) Set(val *WebhookPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPostResponse(val *WebhookPostResponse) *NullableWebhookPostResponse {
	return &NullableWebhookPostResponse{value: val, isSet: true}
}

func (v NullableWebhookPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


