/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
)

// checks if the OrderOrderIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderOrderIdPatchRequest{}

// OrderOrderIdPatchRequest struct for OrderOrderIdPatchRequest
type OrderOrderIdPatchRequest struct {
	Status OrderStatus `json:"status"`
}

// NewOrderOrderIdPatchRequest instantiates a new OrderOrderIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderOrderIdPatchRequest(status OrderStatus) *OrderOrderIdPatchRequest {
	this := OrderOrderIdPatchRequest{}
	this.Status = status
	return &this
}

// NewOrderOrderIdPatchRequestWithDefaults instantiates a new OrderOrderIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderOrderIdPatchRequestWithDefaults() *OrderOrderIdPatchRequest {
	this := OrderOrderIdPatchRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *OrderOrderIdPatchRequest) GetStatus() OrderStatus {
	if o == nil {
		var ret OrderStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OrderOrderIdPatchRequest) GetStatusOk() (*OrderStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OrderOrderIdPatchRequest) SetStatus(v OrderStatus) {
	o.Status = v
}

func (o OrderOrderIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderOrderIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableOrderOrderIdPatchRequest struct {
	value *OrderOrderIdPatchRequest
	isSet bool
}

func (v NullableOrderOrderIdPatchRequest) Get() *OrderOrderIdPatchRequest {
	return v.value
}

func (v *NullableOrderOrderIdPatchRequest) Set(val *OrderOrderIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderOrderIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderOrderIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderOrderIdPatchRequest(val *OrderOrderIdPatchRequest) *NullableOrderOrderIdPatchRequest {
	return &NullableOrderOrderIdPatchRequest{value: val, isSet: true}
}

func (v NullableOrderOrderIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderOrderIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


