/*
Evermile Commercial Quotes and Booking API

This is Evermile's commercial API for handling delivery quotes and orders

API version: 1.0
Contact: support@evermile.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package EvermileClient

import (
	"encoding/json"
	"time"
)

// checks if the OrderDeliveredCallbackResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDeliveredCallbackResp{}

// OrderDeliveredCallbackResp struct for OrderDeliveredCallbackResp
type OrderDeliveredCallbackResp struct {
	// The time this callback was sent in ISO8601 format
	Timestamp time.Time `json:"timestamp"`
	// The ID of the order
	OrderId string `json:"orderId"`
}

// NewOrderDeliveredCallbackResp instantiates a new OrderDeliveredCallbackResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDeliveredCallbackResp(timestamp time.Time, orderId string) *OrderDeliveredCallbackResp {
	this := OrderDeliveredCallbackResp{}
	this.Timestamp = timestamp
	this.OrderId = orderId
	return &this
}

// NewOrderDeliveredCallbackRespWithDefaults instantiates a new OrderDeliveredCallbackResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDeliveredCallbackRespWithDefaults() *OrderDeliveredCallbackResp {
	this := OrderDeliveredCallbackResp{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *OrderDeliveredCallbackResp) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *OrderDeliveredCallbackResp) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *OrderDeliveredCallbackResp) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetOrderId returns the OrderId field value
func (o *OrderDeliveredCallbackResp) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *OrderDeliveredCallbackResp) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *OrderDeliveredCallbackResp) SetOrderId(v string) {
	o.OrderId = v
}

func (o OrderDeliveredCallbackResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDeliveredCallbackResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["orderId"] = o.OrderId
	return toSerialize, nil
}

type NullableOrderDeliveredCallbackResp struct {
	value *OrderDeliveredCallbackResp
	isSet bool
}

func (v NullableOrderDeliveredCallbackResp) Get() *OrderDeliveredCallbackResp {
	return v.value
}

func (v *NullableOrderDeliveredCallbackResp) Set(val *OrderDeliveredCallbackResp) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDeliveredCallbackResp) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDeliveredCallbackResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDeliveredCallbackResp(val *OrderDeliveredCallbackResp) *NullableOrderDeliveredCallbackResp {
	return &NullableOrderDeliveredCallbackResp{value: val, isSet: true}
}

func (v NullableOrderDeliveredCallbackResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDeliveredCallbackResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


